[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
